
/*---------------------------------DROP TABLE-----------------------------------*/

/*
DROP TABLE T_ODS_SUPERMERCADO CASCADE CONSTRAINTS;
DROP TABLE T_ODS_ALIMENTO CASCADE CONSTRAINTS;
DROP TABLE T_ODS_RESERVA CASCADE CONSTRAINTS;
DROP TABLE T_ODS_INSTITUICAO CASCADE CONSTRAINTS;
DROP TABLE T_ODS_ESTOQUE CASCADE CONSTRAINTS;
DROP TABLE T_ODS_RESERVA_ESTOQUE CASCADE CONSTRAINTS;
*/

/*--------------------------CREATE TABLE E ALTER TABLE--------------------------*/

CREATE TABLE T_ODS_SUPERMERCADO(
    CD_MERCADO      NUMBER(5)       NOT NULL,
    NM_MERCADO    VARCHAR2(30)      NOT NULL
);

ALTER TABLE T_ODS_SUPERMERCADO 
    ADD CONSTRAINT PK_ODS_SUPERMERCADO 
PRIMARY KEY ( CD_MERCADO );

SELECT * FROM T_ODS_SUPERMERCADO;

/*-------------------------------------------------------------------------------*/

CREATE TABLE T_ODS_ESTOQUE(
    CD_ESTOQUE      NUMBER(5)       NOT NULL,
    DT_ENTRADA      DATE            NOT NULL,
    DT_VALIDADE     DATE            NOT NULL,
    QT_ALIMENTO     NUMBER(8)       NOT NULL
);

ALTER TABLE T_ODS_ESTOQUE 
    ADD CONSTRAINT PK_ODS_ESTOQUE 
PRIMARY KEY ( CD_ESTOQUE );

SELECT * FROM T_ODS_ESTOQUE;

/*-------------------------------------------------------------------------------*/

CREATE TABLE T_ODS_ALIMENTO(
    CD_ALIMENTO     NUMBER(5)       NOT NULL,
    CD_MERCADO      NUMBER(5)       NOT NULL,
    CD_ESTOQUE      NUMBER(5)       NOT NULL,
    DT_FABRICACAO   DATE            NOT NULL,
    DT_VALIDADE     DATE            NOT NULL,
    NM_ALIMENTO     VARCHAR2(30)    NOT NULL,
    DS_ALIMENTO     VARCHAR2(12)    NOT NULL
);

ALTER TABLE T_ODS_ALIMENTO
    ADD CONSTRAINT PK_ODS_ALIMENTO
PRIMARY KEY ( CD_ALIMENTO );

--CRIAR CONSTRAINT UNIQUE ALIMENTO
    ALTER TABLE T_ODS_ALIMENTO
ADD CONSTRAINT UN_ODS_NM_ALIMENTO
        UNIQUE (NM_ALIMENTO);
        
--CRIAR A CONSTRAINT CHECK ALIMENTO
    ALTER TABLE T_ODS_ALIMENTO
ADD CONSTRAINT CK_ODS_DS_ALIMENTO
        CHECK (DS_ALIMENTO = 'IN NATURA' OR DS_ALIMENTO = 'PROCESSADO');

SELECT * FROM T_ODS_ALIMENTO;

/*-------------------------------------------------------------------------------*/

CREATE TABLE T_ODS_INSTITUICAO(
    CD_INSTITUICAO     NUMBER(5)       NOT NULL,
    NM_INSTITUICAO     VARCHAR2(30)    NOT NULL
);

ALTER TABLE T_ODS_INSTITUICAO
    ADD CONSTRAINT PK_ODS_INSTITUICAO
PRIMARY KEY ( CD_INSTITUICAO );

--CRIAR CONSTRAINT UNIQUE ALIMENTO
    ALTER TABLE T_ODS_INSTITUICAO
ADD CONSTRAINT UN_ODS_NM_INSTITUICAO
        UNIQUE (NM_INSTITUICAO);

SELECT * FROM T_ODS_INSTITUICAO;

/*-------------------------------------------------------------------------------*/

CREATE TABLE T_ODS_RESERVA(
    CD_RESERVA          NUMBER(5)       NOT NULL,
    CD_INSTITUICAO      NUMBER(5)       NOT NULL,
    QT_ALIMENTO         NUMBER(8)       NOT NULL
);

ALTER TABLE T_ODS_RESERVA
    ADD CONSTRAINT PK_ODS_RESERVA
PRIMARY KEY ( CD_RESERVA );

SELECT * FROM T_ODS_RESERVA;

/*-------------------------------------------------------------------------------*/

CREATE TABLE T_ODS_RESERVA_ESTOQUE(
    CD_RESERVA          NUMBER(5)       NOT NULL,
    CD_ESTOQUE          NUMBER(5)       NOT NULL,
    QT_ALIMENTO         NUMBER(8)       NOT NULL
);

SELECT * FROM T_ODS_RESERVA_ESTOQUE;

/*-----------------------------CHAVES ESTRANGEIRAS------------------------------*/
      
    ALTER TABLE T_ODS_RESERVA
ADD CONSTRAINT FK_ODS_RESERVA_INSTITUICAO
    FOREIGN KEY (CD_INSTITUICAO)
    REFERENCES T_ODS_INSTITUICAO (CD_INSTITUICAO);
    
    ALTER TABLE T_ODS_ALIMENTO
ADD CONSTRAINT FK_ODS_ALIMENTO_SUPERMERCADO
    FOREIGN KEY (CD_MERCADO)
    REFERENCES T_ODS_SUPERMERCADO (CD_MERCADO);

    ALTER TABLE T_ODS_ALIMENTO
ADD CONSTRAINT FK_ODS_ALIMENTO_ESTOQUE
    FOREIGN KEY (CD_ESTOQUE)
    REFERENCES T_ODS_ESTOQUE (CD_ESTOQUE);

    ALTER TABLE T_ODS_RESERVA_ESTOQUE
ADD CONSTRAINT FK_ODS_RESERVA_ESTOQUE_ESTOQUE
    FOREIGN KEY (CD_ESTOQUE)
    REFERENCES T_ODS_ESTOQUE (CD_ESTOQUE);

    ALTER TABLE T_ODS_RESERVA_ESTOQUE
ADD CONSTRAINT FK_ODS_RESERVA_ESTOQUE_RESERVA
    FOREIGN KEY (CD_RESERVA)
    REFERENCES T_ODS_RESERVA (CD_RESERVA);



